package com.zanoafnan.submission1expert.core.utils

import com.zanoafnan.submission1expert.core.data.source.local.entity.MealEntity
import com.zanoafnan.submission1expert.core.domain.model.Meal
import com.zanoafnan.submission1expert.core.domain.model.MealsItem

object DataMapper {

    fun mapResponsesToEntities(input: List<MealsItem>): List<MealEntity> {
        val mealList = ArrayList<MealEntity>()
        input.map {
            val meal = MealEntity(
                idMeal = it.idMeal,
                strMeal = it.strMeal,
                strDrinkAlternate = it.strDrinkAlternate,
                strCategory = it.strCategory,
                strArea = it.strArea,
                strInstructions = it.strInstructions,
                strMealThumb = it.strMealThumb,
                strTags = it.strTags,
                strYoutube = it.strYoutube,
                strIngredient1 = it.strIngredient1,
                strIngredient2 = it.strIngredient2,
                strIngredient3 = it.strIngredient3,
                strIngredient4 = it.strIngredient4,
                strIngredient5 = it.strIngredient5,
                strIngredient6 = it.strIngredient6,
                strIngredient7 = it.strIngredient7,
                strIngredient8 = it.strIngredient8,
                strIngredient9 = it.strIngredient9,
                strIngredient10 = it.strIngredient10,
                strIngredient11 = it.strIngredient11,
                strIngredient12 = it.strIngredient12,
                strIngredient13 = it.strIngredient13,
                strIngredient14 = it.strIngredient14,
                strIngredient15 = it.strIngredient15,
                strIngredient16 = it.strIngredient16,
                strIngredient17 = it.strIngredient17,
                strIngredient18 = it.strIngredient18,
                strIngredient19 = it.strIngredient19,
                strIngredient20 = it.strIngredient20,
                strMeasure1 = it.strMeasure1,
                strMeasure2 = it.strMeasure2,
                strMeasure3 = it.strMeasure3,
                strMeasure4 = it.strMeasure4,
                strMeasure5 = it.strMeasure5,
                strMeasure6 = it.strMeasure6,
                strMeasure7 = it.strMeasure7,
                strMeasure8 = it.strMeasure8,
                strMeasure9 = it.strMeasure9,
                strMeasure10 = it.strMeasure10,
                strMeasure11 = it.strMeasure11,
                strMeasure12 = it.strMeasure12,
                strMeasure13 = it.strMeasure13,
                strMeasure14 = it.strMeasure14,
                strMeasure15 = it.strMeasure15,
                strMeasure16 = it.strMeasure16,
                strMeasure17 = it.strMeasure17,
                strMeasure18 = it.strMeasure18,
                strMeasure19 = it.strMeasure19,
                strMeasure20 = it.strMeasure20,
                strSource = it.strSource,
                strImageSource = it.strImageSource,
                strCreativeCommonsConfirmed = it.strCreativeCommonsConfirmed,
                dateModified = it.dateModified,
                isFavorite = it.isFavorite

            )
            mealList.add(meal)
        }
        return mealList
    }

    fun mapEntitiesToDomain(input: @JvmSuppressWildcards List<MealEntity>): List<Meal> =
        input.map {
            Meal(
                idMeal = it.idMeal,
                strMeal = it.strMeal,
                strDrinkAlternate = it.strDrinkAlternate,
                strCategory = it.strCategory,
                strArea = it.strArea,
                strInstructions = it.strInstructions,
                strMealThumb = it.strMealThumb,
                strTags = it.strTags,
                strYoutube = it.strYoutube,
                strIngredient1 = it.strIngredient1,
                strIngredient2 = it.strIngredient2,
                strIngredient3 = it.strIngredient3,
                strIngredient4 = it.strIngredient4,
                strIngredient5 = it.strIngredient5,
                strIngredient6 = it.strIngredient6,
                strIngredient7 = it.strIngredient7,
                strIngredient8 = it.strIngredient8,
                strIngredient9 = it.strIngredient9,
                strIngredient10 = it.strIngredient10,
                strIngredient11 = it.strIngredient11,
                strIngredient12 = it.strIngredient12,
                strIngredient13 = it.strIngredient13,
                strIngredient14 = it.strIngredient14,
                strIngredient15 = it.strIngredient15,
                strIngredient16 = it.strIngredient16,
                strIngredient17 = it.strIngredient17,
                strIngredient18 = it.strIngredient18,
                strIngredient19 = it.strIngredient19,
                strIngredient20 = it.strIngredient20,
                strMeasure1 = it.strMeasure1,
                strMeasure2 = it.strMeasure2,
                strMeasure3 = it.strMeasure3,
                strMeasure4 = it.strMeasure4,
                strMeasure5 = it.strMeasure5,
                strMeasure6 = it.strMeasure6,
                strMeasure7 = it.strMeasure7,
                strMeasure8 = it.strMeasure8,
                strMeasure9 = it.strMeasure9,
                strMeasure10 = it.strMeasure10,
                strMeasure11 = it.strMeasure11,
                strMeasure12 = it.strMeasure12,
                strMeasure13 = it.strMeasure13,
                strMeasure14 = it.strMeasure14,
                strMeasure15 = it.strMeasure15,
                strMeasure16 = it.strMeasure16,
                strMeasure17 = it.strMeasure17,
                strMeasure18 = it.strMeasure18,
                strMeasure19 = it.strMeasure19,
                strMeasure20 = it.strMeasure20,
                strSource = it.strSource,
                strImageSource = it.strImageSource,
                strCreativeCommonsConfirmed = it.strCreativeCommonsConfirmed,
                dateModified = it.dateModified,
                isFavorite = it.isFavorite

            )
        }

    fun mapDomainToEntity(input: Meal) = MealEntity(
        idMeal = input.idMeal,
        strMeal = input.strMeal,
        strDrinkAlternate = input.strDrinkAlternate,
        strCategory = input.strCategory,
        strArea = input.strArea,
        strInstructions = input.strInstructions,
        strMealThumb = input.strMealThumb,
        strTags = input.strTags,
        strYoutube = input.strYoutube,
        strIngredient1 = input.strIngredient1,
        strIngredient2 = input.strIngredient2,
        strIngredient3 = input.strIngredient3,
        strIngredient4 = input.strIngredient4,
        strIngredient5 = input.strIngredient5,
        strIngredient6 = input.strIngredient6,
        strIngredient7 = input.strIngredient7,
        strIngredient8 = input.strIngredient8,
        strIngredient9 = input.strIngredient9,
        strIngredient10 = input.strIngredient10,
        strIngredient11 = input.strIngredient11,
        strIngredient12 = input.strIngredient12,
        strIngredient13 = input.strIngredient13,
        strIngredient14 = input.strIngredient14,
        strIngredient15 = input.strIngredient15,
        strIngredient16 = input.strIngredient16,
        strIngredient17 = input.strIngredient17,
        strIngredient18 = input.strIngredient18,
        strIngredient19 = input.strIngredient19,
        strIngredient20 = input.strIngredient20,
        strMeasure1 = input.strMeasure1,
        strMeasure2 = input.strMeasure2,
        strMeasure3 = input.strMeasure3,
        strMeasure4 = input.strMeasure4,
        strMeasure5 = input.strMeasure5,
        strMeasure6 = input.strMeasure6,
        strMeasure7 = input.strMeasure7,
        strMeasure8 = input.strMeasure8,
        strMeasure9 = input.strMeasure9,
        strMeasure10 = input.strMeasure10,
        strMeasure11 = input.strMeasure11,
        strMeasure12 = input.strMeasure12,
        strMeasure13 = input.strMeasure13,
        strMeasure14 = input.strMeasure14,
        strMeasure15 = input.strMeasure15,
        strMeasure16 = input.strMeasure16,
        strMeasure17 = input.strMeasure17,
        strMeasure18 = input.strMeasure18,
        strMeasure19 = input.strMeasure19,
        strMeasure20 = input.strMeasure20,
        strSource = input.strSource,
        strImageSource = input.strImageSource,
        strCreativeCommonsConfirmed = input.strCreativeCommonsConfirmed,
        dateModified = input.dateModified,
        isFavorite = input.isFavorite
    )


}